config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/" => "devise/sessions#new"
  end
  resources :users, only: [:show, :edit, :update]
  get '/users/:user_id/skills', to: 'skills#index', as: 'user_skills'
  get '/users/:user_id/skills/:category/new', to: 'skills#new', as: 'new_user_skill'
  post '/users/:user_id/skills/:category/create', to: 'skills#create', as: 'create_user_skill'
  put '/users/:user_id/skills/:id/update', to: 'skills#update', as: 'update_user_skill'
  delete 'users/:user_id/skills/:id', to: 'skills#destroy', as: 'delete_skill'








  # get "/" => "users#show"
  # get "/users/#{id}/edit", to: "users#edit", as: "edit_user"
  # # get "/user/edit" => "users#edit"
  # put "/user/update" => "users#update"

  # get "/users/:id/edit", to: "users#edit", as: "edit_user"

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  enum category: { backend: 0, frontend: 1, infrastructure: 2 }

  validates :skill, presence: true
  validates :learning_time, presence: true, numericality: { greater_than_or_equal_to: 1 }

  scope :for_month, ->(month) { where("EXTRACT(MONTH FROM created_at) = ?", month) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :skills

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  validates :introduction, length: { minimum: 50, maximum: 199 }, on: :update
         
  # with_options on: :registrations do
    validates :name, presence: :true       
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i       
    validates :email, presence: true, uniqueness: true,
              format:{ with: VALID_EMAIL_REGEX, message: "メールアドレスに不正な値が入力されています"}

    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i
    validates :password, presence: true,
              format: { with: VALID_PASSWORD_REGEX,
                message: "は英数字を含む8文字以上で設定してください"}, if: :password_required?
  # end     

  def password_required?
    new_record? || password.present? || password_confirmation.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) 
    end

    def after_sign_in_path_for(resource) 
      user_path(id:current_user)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  skip_before_action :verify_authenticity_token

  def index
    @selected_month = params[:month].to_i 
    @selected_month = Date.today.month if @selected_month.zero?

    @backend_skills = @user.skills.backend.for_month(@selected_month)
    @frontend_skills = @user.skills.frontend.for_month(@selected_month)
    @infrastructure_skills = @user.skills.infrastructure.for_month(@selected_month)
  end

  def new
    @skill = @user.skills.build
    @category = params[:category]
    @category_japanese = I18n.t("enums.skill.category.#{@category}")
  end

  def create
    @skill = @user.skills.build(skill_params)
    @skill.category = params[:skill][:category]
    @category = @skill.category
    @category_japanese = I18n.t("enums.skill.category.#{@category}")
    if @skill.save
      modal_message = "#{@category_japanese}に#{@skill.skill}を#{@skill.learning_time}分で追加しました！"
      render json: { modal_message: modal_message }
    else
      render json: { errors: @skill.errors.full_messages }, status: :unprocessable_entity
    end
  end  

  def update
    @skill = Skill.find(params[:id])
    
    if @skill.update(skill_update_params)
      skill_name = @skill.skill
      modal_message = "#{skill_name}の学習時間を保存しました！"
      render json: { modal_message: modal_message }
    else
      render json: { errors: @skill.errors.full_messages }, status: :unprocessable_entity
    end
  end
   
  def destroy
    @skill = Skill.find(params[:id])
    
    if @skill.destroy
      skill_name = @skill.skill
      modal_message = "#{skill_name}を削除しました。"
      render json: { modal_message: modal_message }
    else
      render json: { errors: "削除に失敗しました" }, status: :unprocessable_entity
    end
  end  


  private

  def set_user
    @user = current_user
  end

  def skill_params
    params.require(:skill).permit(:skill, :learning_time, :category)
  end

  def skill_update_params 
    params.require(:skill).permit(:learning_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:top, :show, :edit]

  def top 
    
  end

  def show
    @user = current_user

    current_month = Date.today.month
    last_month = 1.month.ago.month
    last_last_month = 2.months.ago.month

    @backend_data_current_month = @user.skills.backend.for_month(current_month).sum(:learning_time)
    @backend_data_last_month = @user.skills.backend.for_month(last_month).sum(:learning_time)
    @backend_data_last_last_month = @user.skills.backend.for_month(last_last_month).sum(:learning_time)

    @frontend_data_current_month = @user.skills.frontend.for_month(current_month).sum(:learning_time)
    @frontend_data_last_month = @user.skills.frontend.for_month(last_month).sum(:learning_time)
    @frontend_data_last_last_month = @user.skills.frontend.for_month(last_last_month).sum(:learning_time)

    @infrastructure_data_current_month = @user.skills.infrastructure.for_month(current_month).sum(:learning_time)
    @infrastructure_data_last_month = @user.skills.infrastructure.for_month(last_month).sum(:learning_time)
    @infrastructure_data_last_last_month = @user.skills.infrastructure.for_month(last_last_month).sum(:learning_time)

  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.introduction = params[:introduction]

    if @user.update(user_params)
      flash[:notice] = "自己紹介文を編集しました"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit, status: :unprocessable_entity 
    end
  end

  private
  def user_params
    params.require(:user).permit(:introduction, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
    <header>
      <div class="header-wrapper">
          <% if user_signed_in? %>
            <%= link_to "My Portfolio", user_path(current_user), class: "header-title" %> 
            <%= button_to "ログアウト", destroy_user_session_path, { method: :delete, class: "header-logout" }%>
          <% else %>
            <h1 class="header-title">My Portfolio</h1>  
            <%= link_to "ログイン", new_user_session_path, { method: :get, class: "header-login" } %> 
        <% end %>
      </div>
    </header>
    <% if flash.present? %>
      <div class="flash">
        <% flash.each do |key, value| %>
          <div class="<%= key %>">
            <%= value %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <% if user_signed_in? %>
        <p class="footer-title"><%= "#{current_user.name}'s portfolio site" %></p>
      <% else %>
        <p class="footer-title">user name's portfolio site</p>
      <% end %>
    </footer>
</html>

app/views/skills/index.html.erb
<div class="skill-wrapper">
  <% current_month = Date.today.strftime("%m").to_i %>
  <% selected_month = params[:month].to_i || current_month %>
  <select id="month-selector" onchange="changeMonth()">
    <% (0..2).each do |month_ago| %>
      <% month = current_month - month_ago %>
      <% selected = month == selected_month ? 'selected' : nil %>
      <option value="<%= month %>" <%= selected %>><%= "#{month}月" %></option>
    <% end %>
  </select>

  <div class="category">
    <div class="skill-header">
      <div class="skill-header-right">
        <p class="skill-title">バックエンド</p>
      </div>
      <% if selected_month == current_month %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'backend'), class: "button-new-skill" %>
      <% elsif selected_month != (current_month - 1) && selected_month != (current_month - 2) %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'backend'), class: "button-new-skill" %>
      <% end %>
    </div>
    <div class="skill-cards">
      <div class="card-header">
        <p class="card-column">項目名</p>
        <p class="card-column">学習時間</p>
      </div>
      <% @backend_skills.each do |skill| %>
        <div class="skill-card" data-skill-id="<%= skill.id %>">
          <p class="skill-name"><%= skill.skill %></p>
          <%= form_for skill, url: update_user_skill_path(user_id: @user.id, id: skill.id), method: :put, data: { turbo: false, skill_id: skill.id } do |f| %>
            <p class="learning-time">
              <%= f.number_field :learning_time, min: 1, class: 'learning-time-field', id: "learning_time_#{skill.id}" %>
            </p>
            <div class="update-skill-field">
              <%= f.submit "学習時間を保存する", class: "update-learning-time" %>
            </div>
          <% end %>
          <div class="delete-skill-field">
            <%= button_to "削除する", delete_skill_path(user_id: @user.id, id: skill.id), method: :delete, class: "delete-skill", data: { skill_id: skill.id } %>
          </div>  
        </div>
      <% end %>
    </div>
  </div>
  <div class="category">
    <div class="skill-header">
      <div class="skill-header-right">
        <p class="skill-title">フロントエンド</p>
      </div>
      <% if selected_month == current_month %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'frontend'), class: "button-new-skill" %>
      <% elsif selected_month != (current_month - 1) && selected_month != (current_month - 2) %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'frontend'), class: "button-new-skill" %>
      <% end %>
      </div>
    <div class="skill-cards">
      <div class="card-header">
        <p class="card-column">項目名</p>
        <p class="card-column">学習時間</p>
      </div>
      <% @frontend_skills.each do |skill| %>
        <div class="skill-card" data-skill-id="<%= skill.id %>">
          <p class="skill-name"><%= skill.skill %></p>
          <%= form_for skill, url: update_user_skill_path(user_id: @user.id, id: skill.id), method: :put, data: { turbo: false, skill_id: skill.id } do |f| %>
            <p class="learning-time">
              <%= f.number_field :learning_time, min: 1, class: 'learning-time-field', id: "learning_time_#{skill.id}" %>
            </p>
            <div class="update-skill-field">
              <%= f.submit "学習時間を保存する", class: "update-learning-time" %>
            </div>
          <% end %>
          <div class="delete-skill-field">
            <%= button_to "削除する", delete_skill_path(user_id: @user.id, id: skill.id), method: :delete, class: "delete-skill", data: { skill_id: skill.id } %>
          </div>  
        </div>
      <% end %>
    </div>
  </div>
  <div class="category">
    <div class="skill-header">
      <div class="skill-header-right">
        <p class="skill-title">インフラ</p>
      </div>
      <% if selected_month == current_month %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'infrastructure'), class: "button-new-skill" %>
      <% elsif selected_month != (current_month - 1) && selected_month != (current_month - 2) %>
        <%= link_to "項目を追加する", new_user_skill_path(user_id: @user.id, category: 'infrastructure'), class: "button-new-skill" %>
      <% end %>
      </div>
    <div class="skill-cards">
      <div class="card-header">
        <p class="card-column">項目名</p>
        <p class="card-column">学習時間</p>
      </div>
      <% @infrastructure_skills.each do |skill| %>
        <div class="skill-card" data-skill-id="<%= skill.id %>">
          <p class="skill-name"><%= skill.skill %></p>
          <%= form_for skill, url: update_user_skill_path(user_id: @user.id, id: skill.id), method: :put, data: { turbo: false, skill_id: skill.id } do |f| %>
            <p class="learning-time">
              <%= f.number_field :learning_time, min: 1, class: 'learning-time-field', id: "learning_time_#{skill.id}" %>
            </p>
            <div class="update-skill-field">
              <%= f.submit "学習時間を保存する", class: "update-learning-time" %>
            </div>
          <% end %>
          <div class="delete-skill-field">
            <%= button_to "削除する", delete_skill_path(user_id: @user.id, id: skill.id), method: :delete, class: "delete-skill", data: { skill_id: skill.id } %>
          </div>  
        </div>
      <% end %>
    </div>
  </div>
  <div id="myModal" class="modal" style="display: none;">
    <div class="modal-content">
      <p id="modal-message"></p>
      <button id="return-button" onclick="returnToIndexPage()">編集ページに戻る</button>
    </div>
  </div>
</div>

<script>
  function changeMonth() {
    const selectedMonth = document.getElementById("month-selector").value;
    window.location.href = `<%= user_skills_path(user_id: @user.id) %>?month=${selectedMonth}`;
  }

  function returnToIndexPage() {
    const currentURL = window.location.href;
    window.location.href = currentURL;
  }

  function showModal(message) {
    var modal = document.getElementById("myModal");
    var modalMessage = document.getElementById("modal-message");

    modalMessage.innerHTML = message;
    modal.style.display = "block";
  }

  function hideModal() {
    var modal = document.getElementById("myModal");
    modal.style.display = "none";
  }

  document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".update-learning-time").forEach(function (button) {
    button.addEventListener("click", function (e) {
      e.preventDefault();
      var skillId = button.closest("form").getAttribute("data-skill-id");
      var learningTimeField = document.getElementById("learning_time_" + skillId);
      var inputLearningTime = learningTimeField.value;

      var learningTime = inputLearningTime;

      var form = new FormData();
      form.append("skill[learning_time]", learningTime);

      fetch(`/users/<%= @user.id %>/skills/${skillId}/update`, {
        method: "PUT",
        body: form
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (data) {
          if (data.errors) {
            var errorMessage = data.errors.join('<br>');
            showModal(errorMessage);
          } else if (data.modal_message) {
            showModal(data.modal_message);
          }
        })
        .catch(function (error) {
          console.error(error);
        });
    });
  });
});

  document.querySelectorAll(".delete-skill").forEach(function (button) {
    button.addEventListener("click", function (e) {
      e.preventDefault();
      var skillId = button.getAttribute("data-skill-id");
        fetch(`/users/<%= @user.id %>/skills/${skillId}`, {
          method: "DELETE"
        })
          .then(function (response) {
            return response.json();
          })
          .then(function (data) {
            showModal(data.modal_message);
          })
          .catch(function (error) {
            console.error(error);
          }) 
    });
  });

  document.getElementById("return-button").addEventListener("click", returnToIndexPage);
</script>

app/views/skills/new.html.erb
<p class="page-title"><%= @category_japanese %>に項目を追加</p>
<% if @skill.errors.any? %>
  <ul id="error_explanation">
    <% @skill.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: [@user, @skill], url: create_user_skill_path(user_id: @user.id, category: @category || 'default_category'), local: true, data: { skill_new_form: true }) do |form| %>
  <div class="skill-new-field">
  <%= form.label :skill, "項目名", class: 'label', for: "skill_name" %>
  <%= form.text_field :skill, class: "form-control", id: "skill_name", class: 'form' %>
  </div>

  <div class="skill-new-field">
  <%= form.label :learning_time, "学習時間", class: 'label', for: "learning_time" %>
  <%= form.number_field :learning_time, class: "form-control", step: 1, min: 1, id: "learning_time", class: 'form-number' %>
  <%= form.label :learning_time, "分単位で入力してください", class: 'label', for: "learning_time" %>
  </div>

  <%= form.hidden_field :category, value: @category, id: "category" %>

  <div class="skill-new-submit">
    <%= form.submit "追加する", class: "button-skill-new" %>
  </div>
<% end %>

<div id="myModal" class="modal" style="display: none;">
  <div class="modal-content">
    <p id="modal-message"></p>
    <button id="return-button" onclick="returnToIndexPage()">編集ページに戻る</button>
  </div>
</div>

<script>
  function showModal(message) {
    var modal = document.getElementById("myModal");
    var modalMessage = document.getElementById("modal-message");

    modalMessage.innerHTML = message;
    modal.style.display = "block";
  }

  function hideModal() {
    var modal = document.getElementById("myModal");
    modal.style.display = "none";
  }

  document.addEventListener("DOMContentLoaded", function () {
    var form = document.querySelector("[data-skill-new-form]");
    var returnButton = document.getElementById("return-button");

    form.addEventListener("submit", function (e) {
      e.preventDefault();

      var skillName = document.getElementById("skill_name").value;
      var learningTime = document.getElementById("learning_time").value;
      var category = document.getElementById("category").value;

      fetch(`/users/<%= @user.id %>/skills/${category}/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          skill: {
            skill: skillName,
            learning_time: learningTime,
            category: category,
          },
        }),
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (data) {
          if (data.errors) {
            var errorMessage = data.errors.join('<br>');
            showModal(errorMessage);
            returnButton.textContent = "新規登録画面に戻る";
            returnButton.onclick = function() {
              const currentURL = window.location.href;
              window.location.href = currentURL;
            };
          } else if (data.modal_message) {
            showModal(data.modal_message);
            returnButton.onclick = function() {
            window.location.href = "<%= user_skills_path(@user) %>";
            };
          }
        })
        .catch(function (error) {
          console.error(error);
        });
    });
  });
</script>

app/views/users/edit.html.erb
<p class="page-title">自己紹介を編集する</p>
<% if @user.errors.any? %>
  <ul id="error_explanation">
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user, url: user_path(current_user), method: :put, local: true do |f| %>
  <div class="update-field">
    <%= f.label :introduction, "自己紹介文", class: 'label' %><br />
    <%= f.text_area :introduction, class: 'form-area' %><br />
    <%= f.label :introduction, "50文字以上、200文字未満で入力してください", class: 'label' %><br />
    <%= f.label :avatar, "アバター画像", id: 'avatar-label' %><br />
    <%= f.file_field :avatar %>
    <div class="update">
      <%= f.submit "自己紹介を確定する",  class: 'button-update' %>
    </div>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
 <div class="profile-wrapper"> 
  <div class="introduction-wrapper">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, class: "avatar-image" %>
    <% else %>
      <%= image_tag 'default_avatar.png', class: "avatar-image" %>
    <% end %>
    <div class="introduction-right">
      <p class="top-title">自己紹介</p>
      <p class="introduction"><%= @user.introduction %></p>
      <%= link_to '自己紹介を編集する', edit_user_path(current_user), class: "button-introduction" %>
    </div>
  </div>
  <div class="skill-chart">
    <p class="chart-title">学習チャート</p>
    <%= link_to '編集する', user_skills_path(current_user), class: "button-skills" %>
  </div>
  <div class="chart-wrapper">
    <canvas id="myChart"></canvas>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- app/views/skills/show.html.erb -->

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['先々月', '先月', '今月'],
        datasets: [
          {
            label: 'バックエンド',
            data: [<%= @backend_data_last_last_month %>, <%= @backend_data_last_month %>, <%= @backend_data_current_month %>],
            backgroundColor: 'rgba(247, 157, 157, 0.7)',
            borderWidth: 1
          },
          {
            label: 'フロントエンド',
            data: [<%= @frontend_data_last_last_month %>, <%= @frontend_data_last_month %>, <%= @frontend_data_current_month %>],
            backgroundColor: 'rgba(258, 188, 86, 0.7)',
            borderWidth: 1
          },
          {
            label: 'インフラ',
            data: [<%= @infrastructure_data_last_last_month %>, <%= @infrastructure_data_last_month %>, <%= @infrastructure_data_current_month %>],
            backgroundColor: 'rgba(252, 229, 128, 0.7)',
            borderWidth: 1
          }
        ]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  });
</script>

app/views/users/top.html.erb
<p>users#top</p>